name: Main Workflow

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
  workflow_dispatch: # Allows running manually from Actions tab

jobs:
  # WARNING: do not allow ${{ secrets.* }} in the below sections
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install bats and shellmock
        run: |
          sudo apt-get update
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      - name: Run bats tests for sample-bats
        run: cd sample-bats && bats ./*.bats
      - name: Run bats tests for test
        run: cd test && bats ./*.bats
